### ISSUE TITLE
unavailable

### ISSUE THREAD

**Issue by puleiC** [gorules/zen#177]
![1718266383996](https://github.com/gorules/zen/assets/102528566/e1495e17-cd0f-4408-b4c4-45bd0aac3c2f)

**Comment by puleiC** [comment]
There's no print in the log. I was deployed by helm

**Comment by ivanmiletic** [comment]
Hi @puleiC  i believe this is the issue with BRMS not running in secure context (https). Some browser apis that we use require secure connection / with certificate to be able to run properly.

I believe for testing you can run a chrome in unsecure mode. We will see how to solve this so that brms can run on non https connectections.

**Comment by puleiC** [comment]
@ivanmiletic Thank you for your reply. The problem has been solved. It is the http problem that causes the unavailability. I suggest that you add deployment tips related to https

**Comment by ivanmiletic** [comment]
We will try to update documentation, please bear with us. - we have a few big features coming over next couple of months together with team scaling and also working with our enterprise customers.
