### ISSUE TITLE
Unexpected value from Extract expression

### ISSUE THREAD

**Issue by Gabrieltay** [gorules/zen#293]
Hi GoRules team,

I was trying out the `extract` expression based on the user documentation.

```
extract('2022-02-01', '(d{4})-(d{2})-(d{2})'); // ["2022-02-01", "2022", "02", "01"]
extract('foo.bar', '(w+).(w+)'); // ["foo.bar", "foo", "bar"]
```

However, the output turns out to be `[]`

I had ran this on zen `v0.33.0` as well as the latest `gorules/editor` image, both produced the same behaviour.

I have attached the graph for your reference.

Let me know if I have used the expression in the wrong way. Thanks

[extract_expression.json](https://github.com/user-attachments/files/18105236/extract_expression.json)

**Comment by stefan-gorules** [comment]
Hi @Gabrieltay,

The regex for your use case requires `\w` instead of `w`.

Please see: https://cheatography.com/davechild/cheat-sheets/regular-expressions/. The quickest way to try the regex out is through: https://gorules.io/tools/expression-language.

![CleanShot 2024-12-13 at 14 06 46@2x](https://github.com/user-attachments/assets/bc3ea4f9-bb18-49b7-b21c-96ee422497b9)

**Comment by Gabrieltay** [comment]
Thanks @stefan-gorules. This `expression-language` tool is very useful 👍 

Btw, perhaps you could update your [documentation](https://docs.gorules.io/docs/string#extract) 

The following example was taken from it
```
extract('2022-02-01', '(d{4})-(d{2})-(d{2})'); // ["2022-02-01", "2022", "02", "01"]
extract('foo.bar', '(w+).(w+)'); // ["foo.bar", "foo", "bar"]
```

Will close this issue. Thanks again for the prompt response.
