### ISSUE TITLE
Median Function in expression language

### ISSUE THREAD

**Issue by ivanmiletic** [gorules/zen#45]
Add support for the median function in the expression language.

**Comment by egandro** [comment]
We should really talk (again) about Library function.

That wil solve these problems.

Willing to chat on discord - we can have a video call.

**Comment by stefan-gorules** [comment]
It would not solve the problem that we are talking about above. The request is to allow non-technical users to extract the median value within the decision table. Similarly to how we have:

`avg([1, 1, 4]) -> 2`

We want to expand to
`median([1, 1, 4]) -> 1`

**Comment by egandro** [comment]
For this case, i suggest an expression language. Something like Excel has

sum(), avg(), ... 

There is this package for javascript: https://github.com/AjaniBilby/BNF-parser/blob/master/test/uv/uniview.bnf

You can basically create a parser (like in compiler crafting). The result is something that can be executed in Javascript.

You can create very complex and Excel like thigns eg.g if .. else ... excel-ish things business analysts love to use :) 

Willing to help here.

**Comment by ivanmiletic** [comment]
Hi @egandro we already have expression language, here are references:

https://github.com/gorules/zen/blob/master/core/expression/src/compiler.rs

and implementation:

https://github.com/gorules/zen/blob/master/core/expression/src/vm.rs

We will just extend our expression language and add median and mean. I'm using ticket to track it

**Comment by egandro** [comment]
@ivanmiletic  I was thinking about this the whole day :)

I have a suggestion. Maybe you guys can wirte down a nice Unit Test for a future iteration of this.

Have all of your internal functions for your expression language tested against the equivalend functions within Excel.

From experience, Excel is a can of worms, when it comes to do "math". It would be super cool (since you have Business Analysts working with gorules) to be clear where Excel does math in a different way.

You might not need to implement this "now" but at some point the bug hunting will be much simpler. 

I can imagine discussions like this :) "Excel gives me 14 contracts while >> your << tool gives me 15"

**Comment by stefan-gorules** [comment]
@egandro we can do that, however, the syntax is completely different between both tools. 

We have pretty good and sane coverage with end-to-end tests that are currently in place, we will look into increasing it in the future.

For reference, the engine has about ~80% coverage and the expressions crate has ~78%. We'll likely look into improving it closer to ~85-90% but never aim for 100%.
