### ISSUE TITLE
The Datetime function seasonOfYear() and weekOfMonth() are currently not working in the zen expression language

### ISSUE THREAD

**Issue by Wilfred-Shu** [gorules/zen#70]
I have looked at the source code and cannot find the corresponding functions.
![image](https://github.com/gorules/zen/assets/108380390/e194c7d9-a22c-4ec2-9984-a8131d152571)

**Comment by stefan-gorules** [comment]
Hi thanks, for submitting this. Had a look at it and verified that it's indeed the case.

The functions will be removed as they are not useful, nor easy to extract from `chrono` package.

**Comment by Wilfred-Shu** [comment]
Hi Stefan, thank you for your prompt reply. I was hoping you can fix those functions as it might be useful for some people. If not, please also remove them from the documentation as they were listed out here.
![image](https://github.com/gorules/zen/assets/108380390/67fad401-43a2-4f98-840f-3e555dd6eeb6)

**Comment by stefan-gorules** [comment]
Hi @Wilfred-Shu , we haven't seen the active usages (and the impl was broken), only place where I can see this being useful on top of my head is in retail and promotion logic, e.g.:

During winter -> shipping cost increase 10%,
During summer -> shipping cost decrease 10% 

and similar cases, but seasons are different between countries which will then require 1 additional argument to be passed.

As for `weekOfMonth` it can be useful as well, but we'd need to find a good standard implementation to avoid risk of not getting it right.

For now since both are unused by community, we'll remove and in case there are any requests raised we can bring these functions back.
